### ISSUE TITLE
Adding `android` to the PATH (Mac OSX)

### ISSUE THREAD

**Issue by csengineer13** [clef/clef-native-sample-cordova#8]
The readme mentions using the following method to add `android` as an accessible command from the terminal/command line:

`export PATH=/Users/<USER>/Library/Android/sdk/tools/android:$PATH`

Unfortunately, this didn't do the trick for my team. We had more success with the following:

https://spring.io/guides/gs/android/

Which materialized as the following steps:

*On Mac OSX:*

1. Open terminal
2. `cd` (navigate to root)
3. `nano .bash_profile`
4. Add the following to the file:

`export PATH=/Users/<user>/Library/Android/sdk/tools:$PATH`

5. Ctrl + o (to save)
6. Ctrl + x (to exit)
7. Close & reopen terminal
8. `android` (to verify correct path)

Note: It appears Android SDK tools are not installed until Android Studio is ran for the first time. IE. It needs to be opened at least once after the initial install.

**Comment by landakram** [comment]
Thanks for the tips @csengineer13! It looks like I copied the path incorrectly. I updated the docs with the path (`/Users/<user>/Library/Android/sdk/tools`) that you specified.
